// AUTOGENERATED FILE: easyjson marshaller/unmarshallers.

package sockets

import (
	json "encoding/json"
	easyjson "github.com/mailru/easyjson"
	jlexer "github.com/mailru/easyjson/jlexer"
	jwriter "github.com/mailru/easyjson/jwriter"
)

// suppress unused package warning
var (
	_ *json.RawMessage
	_ *jlexer.Lexer
	_ *jwriter.Writer
	_ easyjson.Marshaler
)

func easyjson7e4422e8DecodeGithubComDustinblackmanStreamrollerSockets(in *jlexer.Lexer, out *SocketMessage) {
	isTopLevel := in.IsStart()
	if in.IsNull() {
		if isTopLevel {
			in.Consumed()
		}
		in.Skip()
		return
	}
	in.Delim('{')
	for !in.IsDelim('}') {
		key := in.UnsafeString()
		in.WantColon()
		if in.IsNull() {
			in.Skip()
			in.WantComma()
			continue
		}
		switch key {
		case "message":
			out.Message = string(in.String())
		case "source":
			out.Source = string(in.String())
		case "user":
			out.User = string(in.String())
		default:
			in.SkipRecursive()
		}
		in.WantComma()
	}
	in.Delim('}')
	if isTopLevel {
		in.Consumed()
	}
}
func easyjson7e4422e8EncodeGithubComDustinblackmanStreamrollerSockets(out *jwriter.Writer, in SocketMessage) {
	out.RawByte('{')
	first := true
	_ = first
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"message\":")
	out.String(string(in.Message))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"source\":")
	out.String(string(in.Source))
	if !first {
		out.RawByte(',')
	}
	first = false
	out.RawString("\"user\":")
	out.String(string(in.User))
	out.RawByte('}')
}

// MarshalJSON supports json.Marshaler interface
func (v SocketMessage) MarshalJSON() ([]byte, error) {
	w := jwriter.Writer{}
	easyjson7e4422e8EncodeGithubComDustinblackmanStreamrollerSockets(&w, v)
	return w.Buffer.BuildBytes(), w.Error
}

// MarshalEasyJSON supports easyjson.Marshaler interface
func (v SocketMessage) MarshalEasyJSON(w *jwriter.Writer) {
	easyjson7e4422e8EncodeGithubComDustinblackmanStreamrollerSockets(w, v)
}

// UnmarshalJSON supports json.Unmarshaler interface
func (v *SocketMessage) UnmarshalJSON(data []byte) error {
	r := jlexer.Lexer{Data: data}
	easyjson7e4422e8DecodeGithubComDustinblackmanStreamrollerSockets(&r, v)
	return r.Error()
}

// UnmarshalEasyJSON supports easyjson.Unmarshaler interface
func (v *SocketMessage) UnmarshalEasyJSON(l *jlexer.Lexer) {
	easyjson7e4422e8DecodeGithubComDustinblackmanStreamrollerSockets(l, v)
}
